config/routes.rb
Rails.application.routes.draw do

  get 'search'=>"searches#search",as: :search
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]
  resources :users, only: [:index,:show,:edit,:update]
  resources :favorites, only: [:create,:destroy]
  resources :book_comments, only: [:create,:destroy]
  resources :relationships, only: [:create,:destroy]
  resources :groups, only: [:new,:create,:index,:edit,:update,:show]
  
  get 'users/:id/follows' => "users#index", as: :follow_list
  get 'users/:id/followers'=>'users#index', as: :follower_list
  
  
  
  get 'messages/:speaker/:target'=>"messages#index",as: :messages
  post 'messages/:speaker/:target'=>"messages#create"
  
  post 'users/:id/post_count'=>"users#post_count",as: :post_count
  post 'join/group/:id'=>"groups#join",as: :join_group
  delete 'out/group/:id'=>"groups#out_group",as: :out_group
  
  get 'notice_an_event/:id'=>"groups#notice_an_event",as: :notice_an_event
  post 'notice_an_event/:id'=>"groups#send_email"
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    
    
    belongs_to :book
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        Favorite.create(:book_id=>params[:id],:user_id=>current_user.id)
        @book = Book.find(params[:id])
        #redirect_back fallback_location: root_path
        #return @book
    
    end
    
    def destroy
        favorite = Favorite.where(:book_id=>params[:id],:user_id=>current_user.id).first
        favorite.delete()
        @book = Book.find(params[:id])
        #redirect_back fallback_location: root_path
        #return @book
    end
    
    private
    
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite-btn.html.erb
<%if book.favorite_users.pluck(:user_id).include?(current_user.id) %>
<%= link_to favorite_path(:id=>book.id), method: :DELETE, remote: true do %><i class="fa-solid fa-heart"></i><% end %>
<% else %>
<%= link_to favorites_path(:id=>book.id), method: :POST, remote: true do %><i class="fa-regular fa-heart"></i><% end %>
<% end %>
<%= book.favorites.length %>

app/views/favorites/create.js.erb
$('.favorite-btn[data-book="<%= escape_javascript(@book.id) %>"]').html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$('.favorite-btn[data-book="<%= escape_javascript(@book.id) %>"]').html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book}) %>");