config/routes.rb
Rails.application.routes.draw do

  get 'search'=>"searches#search",as: :search
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]
  resources :users, only: [:index,:show,:edit,:update]
  resources :favorites, only: [:create,:destroy]
  resources :book_comments, only: [:create,:destroy]
  resources :relationships, only: [:create,:destroy]
  resources :groups, only: [:new,:create,:index,:edit,:update,:show]
  
  get 'users/:id/follows' => "users#index", as: :follow_list
  get 'users/:id/followers'=>'users#index', as: :follower_list
  
  
  
  get 'messages/:speaker/:target'=>"messages#index",as: :messages
  post 'messages/:speaker/:target'=>"messages#create"
  
  post 'users/:id/post_count'=>"users#post_count",as: :post_count
  post 'join/group/:id'=>"groups#join",as: :join_group
  delete 'out/group/:id'=>"groups#out_group",as: :out_group
  
  get 'notice_an_event/:id'=>"groups#notice_an_event",as: :notice_an_event
  post 'notice_an_event/:id'=>"groups#send_email"
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :group_users
    has_many :users , through: :group_users
    belongs_to :owner, class_name: 'User'
    
    has_one_attached :group_image
      
    def get_group_image
        (group_image.attached?) ? group_image : 'no_image.jpg'
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    
    
    def index
        @groups = Group.all
    end
    
    def new
        
    end
    
    def edit
       @group = Group.find(params[:id]) 
    end
    
    def show
       @group = Group.find(params[:id]) 
    end
    
    def update
       group = Group.find(params[:id])
       group.update(group_params.merge(:owner_id => current_user.id))
       redirect_to groups_path 
    end
    
    def create
        Group.create(group_params.merge(:owner_id => current_user.id))
        redirect_to groups_path
    end
    
    def join
        GroupUser.create(:user_id=>current_user.id,:group_id=>params[:id])
        redirect_to groups_path
    end
    
    def out_group
       group=GroupUser.find_by(:user_id=>current_user.id,:group_id=>params[:id])
       group.delete()
       redirect_to groups_path
    end
    
    def notice_an_event
        @group = Group.find(params[:id])
    end
    
    def send_email
        @group = Group.find(params[:id])
        
    end
    
    private
    
    def group_params
        params.require(:group).permit(:name,:introduction,:group_image)  
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_index.html.erb
<table class='table'>
    <thead>
        <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% groups.each do |group| %>
        <tr>
            <td><%= image_tag group.get_group_image, size: '50x50' %></td>
            <td><%= link_to group.name , group_path(group) %></td>
            <td><%= group.introduction %></td>
            <td>
                <% if group.owner_id == current_user.id %>
                <%= link_to 'edit',edit_group_path(group), {class: "btn btn-info"} %>
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/groups/_show.html.erb
<table class='table'>
    <thead>
        <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><%= image_tag @group.get_group_image, size: '50x50' %></td>
            <td><%= link_to @group.name , group_path(@group) %></td>
            <td><%= @group.introduction %></td>
            <td>
                <p><%= @group.owner.name %></p>
                <% @group.users.each do |user| %>
                    <p><%= user.name %></p>
                <% end %>
            </td>
            <td>
                <% if @group.owner_id == current_user.id %>
                <%= link_to 'edit',edit_group_path(@group), {class: "btn btn-info"} %>
                <% end %>
            </td>
            <td>
                <% if @group.owner_id != current_user.id %>
                    <% if current_user.is_joined(@group.id) %>
                        <%= link_to 'Leave this group',out_group_path(@group), method: :DELETE, class: "btn btn-danger" %>
                    <% else %>
                        <%= link_to 'Join this group',join_group_path(@group), method: :POST, class: "btn btn-info" %>
                    <% end %>
                <% end %>
            </td>
            <td>
                <% if @group.owner_id == current_user.id %>
                <%= link_to 'Notice an Event',notice_an_event_path(@group), {class: "btn btn-info"} %>
                <% end %>
            </td>
        </tr>
    </tbody>
</table>

app/views/groups/edit.html.erb
<div class='container'>

<h2>
    Edit Group
</h2>
<%= form_with model: @group,class: 'form-group' do |f| %>
    <%= f.label :name,'名前',class: 'form-label' %>
    <%= f.text_field :name,class: 'form-control' %>
    <%= f.label :introduction,'紹介文',class: 'form-label' %>
    <%= f.text_area :introduction,class: 'form-control' %>
    <%= f.label :image,'アイコン画像' %><br>
    <%= f.file_field :group_image, class: "form-control-file group_image", accept: 'image/*' %><br>
    <%= f.submit '送信',class: 'btn btn-info mt-4' %>
<% end %>


</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row'>
        <div class='col-md-3'>
            <h2>User info</h2>
            <%= render 'users/info', user: current_user %>

            <h2 class="mt-3">New book</h2>
            <%= render 'books/form', book: @book %>
        </div>
        <div class='col-md-8 offset-md-1'>
            
            <h2><%= @title ? @title : "Groups" %></h2>
            <%= render partial: 'index',locals:{user: current_user,groups: @groups} %>
        </div>
    </div>
</div>

app/views/groups/new.html.erb
<div class='container'>

<h2>
    Create Group
</h2>
<%= form_with model: Group.new,class: 'form-group' do |f| %>
    <%= f.label :name,'名前',class: 'form-label' %>
    <%= f.text_field :name,class: 'form-control' %>
    <%= f.label :introduction,'紹介文',class: 'form-label' %>
    <%= f.text_area :introduction,class: 'form-control' %>
    <%= f.label :image,'アイコン画像' %><br>
    <%= f.file_field :group_image, class: "form-control-file group_image", accept: 'image/*' %><br>
    <%= f.submit '送信',class: 'btn btn-info mt-4' %>
<% end %>


</div>

app/views/groups/notice_an_event.html.erb
<div class='container'>

<h2>
    Event Mail
</h2>
<%= form_with method: :POST,class: 'form-group',url: notice_an_event_path(@group) do |f| %>
    <%= f.label :title,'タイトル',class: 'form-label' %>
    <%= f.text_field :title,class: 'form-control' %>
    <%= f.label :body,'内容',class: 'form-label' %>
    <%= f.text_area :body,class: 'form-control' %>
    <%= f.submit '送信',class: 'btn btn-info mt-4' %>
<% end %>


</div>

app/views/groups/send_email.html.erb
<div class='container'>

    <h2>
        送信しました
    </h2>

    <dl>
        <dt>タイトル</dt>
        <dd><%= params[:title] %></dd>
        <dt>内容</dt>
        <dd><%= params[:body] %></dd>
    </dl>

</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row'>
        <div class='col-md-3'>
            <h2>User info</h2>
            <%= render 'users/info', user: current_user %>

            <h2 class="mt-3">New book</h2>
            <%= render 'books/form', book: @book %>
        </div>
        <div class='col-md-8 offset-md-1'>
            
            <h2>Group Detail</h2>
            <%= render 'show',locals:{group: @group} %>
        </div>
    </div>
</div>