config/routes.rb
Rails.application.routes.draw do

  get 'search'=>"searches#search",as: :search
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]
  resources :users, only: [:index,:show,:edit,:update]
  resources :favorites, only: [:create,:destroy]
  resources :book_comments, only: [:create,:destroy]
  resources :relationships, only: [:create,:destroy]
  resources :groups, only: [:new,:create,:index,:edit,:update,:show]
  
  get 'users/:id/follows' => "users#index", as: :follow_list
  get 'users/:id/followers'=>'users#index', as: :follower_list
  
  
  
  get 'messages/:speaker/:target'=>"messages#index",as: :messages
  post 'messages/:speaker/:target'=>"messages#create"
  
  post 'users/:id/post_count'=>"users#post_count",as: :post_count
  post 'join/group/:id'=>"groups#join",as: :join_group
  delete 'out/group/:id'=>"groups#out_group",as: :out_group
  
  get 'notice_an_event/:id'=>"groups#notice_an_event",as: :notice_an_event
  post 'notice_an_event/:id'=>"groups#send_email"
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :book_accesses, dependent: :destroy
  validates :title,presence: true,length:{minimum: 1}
  validates :body,presence: true,length:{maximum: 200}
  
  has_one_attached :book_image
end

app/models/book_access.rb
class BookAccess < ApplicationRecord
    belongs_to :book
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    
    
    belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :group_users
    has_many :users , through: :group_users
    belongs_to :owner, class_name: 'User'
    
    has_one_attached :group_image
      
    def get_group_image
        (group_image.attached?) ? group_image : 'no_image.jpg'
    end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
    belongs_to :user
    belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :speaker, class_name: "User"
    belongs_to :target, class_name: "User"
    validates :message, presence: true,length: {maximum: 140}
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites
  has_many :book_comments
  has_many :follows, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follow_members, through: :follows, source: :followed
  has_many :follower_members, through: :followers, source: :follower
  

  
  has_many :group_users
  has_many :groups, through: :group_users, source: :group

  
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  def is_joined(group_id)
    self.groups.where('group_id = ?',group_id).length > 0
  end

  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  
  def is_followed_by(user)
    self.followers.pluck('follower_id').include?(user.id)
  end
  
  def posted_at(day)
    self.books.where('books.created_at like ? ',"%#{day}%")
  end
  
  def days_post(days_ago)
    self.books.where('books.created_at <= ?',days_ago.day.ago).where('books.created_at > ?',(days_ago+1).day.ago)
  end
  
  def todays_post
    self.books.where('books.created_at > ?',1.day.ago)
  end
  
  def predays_post
    self.books.where('books.created_at <= ?',1.day.ago).where('books.created_at > ?',2.day.ago)
  end
  
  def this_week_post
    self.books.where('books.created_at > ?',1.week.ago)
  end
  
  def pre_week_post
    self.books.where('books.created_at <= ?',1.week.ago).where('books.created_at > ?',2.week.ago)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def show
    @book = Book.find(params[:id])
    BookAccess.create(:book_id=>@book.id)
  end

  def index
    @books = Book.left_outer_joins(:favorites)
              .select('books.*','sum(case when favorites.created_at >= "'+1.week.ago.to_s+'" then 1 else 0 end) as favorites_count')
              .group('books.id')
              #.order('favorites_count desc')
              
    if !params[:type]
      @books = @books.order('favorites_count desc')
    elsif params[:type] == 'new'
      @books = @books.order('books.created_at desc')
    elsif params[:type] == 'score'
      @books = @books.order('books.score desc')
    end
    
    if params[:tag] && params[:tag]!=''
      @books = @books.where('tag like ?',"%#{params[:tag]}%")
    end
    
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      @book_tmp = @book
      @user = current_user
      flash.now[:notice] = 'error'
      render 'index'
      #redirect_back fallback_location: root_path
    end
  end

  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body,:score,:tag)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end
  
  def post_count
   @user = User.find(params[:id])
   @date = params[:date]
  end

  def index
    @users = User.all
    if request.path.split('/')[3]
      # user_id = request.path.split('/')[2].to_i
      if request.path.split('/')[3] == 'follows'
        @users = User.find(params[:id]).follow_members
        @title = 'follows'
      elsif request.path.split('/')[3]=='followers'
        @users = User.find(params[:id]).follower_members
        @title = 'followers'
      end
    end
    @book = Book.new
  end

  def edit
    if current_user.id.to_i != params[:id].to_i
      redirect_to user_path(current_user)
    end
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model: controller.action_name == 'edit' || controller.action_name == 'update' ? book : Book.new ,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class='form-group'>
    <div id="post_raty"></div>
  </div>
  <div class='form-group'>
    <%= f.label :tag %>
    <%= f.text_field :tag  , class: 'form-control book_tag' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>
<script>
document.addEventListener('turbolinks:load', () => {
  // scriptファイルをどのidの部分に配置するかを指定
  var elem = document.querySelector('#post_raty');
  var opt = {  
    //星画像の指定などのオプションをここに記述,
    path: '/assets',
    scoreName:'book[score]',
    score: <%= j( book ? book.score : 0) %>,
    readOnly: <%= j(controller.action_name == 'edit' ? "true" : "false") %>
   };
   if(elem !== null){
     elem.innerHTML='';
     raty(elem,opt);
   }
});
</script>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <% @book = book %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td><%= book.tag %></td>
        <td><div class='scores' data-score='<%= book.score ? book.score : 0 %>'><%= book.score ? book.score : 0 %></div></td>
        <td class='favorite-btn' data-book='<%= @book.id %>'>
          <%= render 'favorites/favorite-btn',book: @book %>
        </td>
        <td>
          コメント数：<%= book.book_comments.length %>
        </td>
        <td>
          アクセス: <%= book.book_accesses.length %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
document.addEventListener('turbolinks:load', () => {
  // scriptファイルをどのidの部分に配置するかを指定
  var elements = document.querySelectorAll('.scores');
  var opt = {  
    //星画像の指定などのオプションをここに記述,
    path: '/assets',
    scoreName:'book[score]',
    readOnly: true
   };
   if(elements !== null){
     for(el of elements){
       el.innerHTML='';
       raty(el,opt);
     }
   }
});
</script>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= controller.action_name %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %>
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to '新着順' , books_path({:type=>'new'}) %>
      <%= link_to '評価が高い順',books_path({:type=>"score"}) %>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/index.js.erb
alert('hell');

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info' %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td><div id="score_stars"></div></td>
            <td>
              <% if @book.user.id==current_user.id %>
              <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %>
              <% end %>
            </td>
            <td>
              <% if @book.user.id==current_user.id %>
              <%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%>
              <% end %>
            </td>        
            <td class='favorite-btn' data-book='<%= @book.id %>'>
              <%= render 'favorites/favorite-btn',book: @book %>
            </td>
            <td>
              アクセス: <%= @book.book_accesses.length %>
            </td>
        </tr>
      </table>
      <ul>
      <% @book.book_comments.each do |c| %>
      <li>
        <%= c.comment %>
        <% if c.user.id == current_user.id %>  
          <%= link_to 'Destroy', book_comment_path(c), method: :delete %>
        <% end %>
      </li>
      <% end %>
      </ul>
      <%= form_with model: BookComment.new ,url: book_comments_path(:book_id=>params[:id]) do |f| %>
      <%= f.text_area :comment %><br>
      <%= f.submit '送信' %>
      <% end %>
    </div>
  </div>
</div>
<script>
document.addEventListener('turbolinks:load', () => {
  // scriptファイルをどのidの部分に配置するかを指定
  var element = document.querySelector('#score_stars');
  var option = {  
    path: '/assets',
    score: <%= j(@book.score ? @book.score : 0) %>,
    readOnly: true
   };
   if(element){
     element.innerHTML='';
     raty(element,option);
   }
});
</script>

app/views/users/_follow_button.html.erb
  <%if user.is_followed_by(current_user) %>
    <%= link_to relationship_path(:id=>user.id), method: :delete do %>
        <button class='btn btn-warning'>フォロー外す</button>
    <% end %>
  <% else %>
    <%= link_to relationships_path(:id=>user.id), method: :post do %>
        <button class='btn btn-primary'>フォローする</button>
    <% end %>
  <% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数<%= user.follows.length %></td>
        <td>フォロワー数<%= user.followers.length %></td>
        <td>
          <%= render partial: 'follow_button',locals: {user: user } %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<% user = @book && @book.user && controller.controller_name == 'books' ? @book.user : (@user && controller.controller_name=='users' && controller.action_name=='show' ?  @user : current_user)  %>

<table class='table'>
  <tr><%= image_tag current_user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>forllows</th>
    <th>
      <%= link_to follow_list_path(user) do %>
      <%= user.follows.length %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to follower_list_path(user) do %>
      <%= user.followers.length %>
      <% end %>
    </th>
  </tr>
</table>

<div class='row'>
  <div class='col-6'>
    <%= render partial: 'users/follow_button',locals: {user: user } %>
  </div>
  <div class='col-6'>
    <% if current_user.is_followed_by(user) && user.is_followed_by(current_user) %>
    <%= link_to "Chat", messages_path(current_user,user) %>
    <% end %>
  </div>
</div>
　
<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/_post_sum.html.erb
<div class='row'>
    <h2>投稿数の前日比・先週比</h2>
    <table class='table table-striped text-center'>
      <tr>
        <th>今日の投稿数</th>
        <th>昨日の投稿数</th>
        <th>昨日との差</th>
      </tr>
      <tr>
        <td>
          <%= @user.todays_post.length %>
        </td>
        <td>
          <%= @user.predays_post.length %>
        </td>
        <td>
          <%= @user.todays_post.length - @user.predays_post.length %>
        </td>
      </tr>
      <tr>
        <th>今週の投稿数</th>
        <th>先週の投稿数</th>
        <th>先週との差</th>
      </tr>
      <tr>
        <td>
          <%= @user.this_week_post.length %>
        </td>
        <td>
          <%= @user.pre_week_post.length %>
        </td>
        <td>
          <%= @user.this_week_post.length - @user.pre_week_post.length %>
        </td>
      </tr>
    </table>
    
  </div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model: @user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row'>
        <div class='col-md-3'>
            <h2>User info</h2>
            <%= render 'info', user: current_user %>

            <h2 class="mt-3">New book</h2>
            <%= render 'books/form', book: @book %>
        </div>
        <div class='col-md-8 offset-md-1'>
            
            <h2><%= @title ? @title : "Users" %></h2>
            <%= link_to 'グループを作成', new_group_path %>
            <%= render 'index',users: @users %>
        </div>
    </div>
</div>

app/views/users/post_count.js.erb
$(function(){
    if("<%= @date %>".length===0){
        $('#books_count').html('日付を入力してください');
    }else{
        $('#books_count').html("<%= @date %>の投稿数<%= j(@user.posted_at(@date).length) %>冊")
    }
});

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
    <div class='col-md-8 offset-md-4'>
      <%= render 'users/post_sum', user: @user %>
    </div>
    <div class='col-md-8 offset-md-4'>
      <canvas id="myChart" width="400px" height="400px" data-labels='<%= [0,1,2,3,4,5,6].map{|x| (x+1).to_s + '日前' }.reverse.to_json %>' data-data="<%= [0,1,2,3,4,5,6].map{|x| @user.days_post(x).length }.reverse.to_json  %>"></canvas>
    </div>
    <div class='col-md-8 offset-md-4'>
      <%= form_with method: :post , url: post_count_path(@user.id), local: false do |f| %>
      <%= f.date_field :date %>
      <%= f.submit '検索' %>
      <% end %>
      <p id='books_count'></p>
    </div>
  </div>
</div>