config/routes.rb
Rails.application.routes.draw do

  get 'search'=>"searches#search",as: :search
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]
  resources :users, only: [:index,:show,:edit,:update]
  resources :favorites, only: [:create,:destroy]
  resources :book_comments, only: [:create,:destroy]
  resources :relationships, only: [:create,:destroy]
  resources :groups, only: [:new,:create,:index,:edit,:update,:show]
  
  get 'users/:id/follows' => "users#index", as: :follow_list
  get 'users/:id/followers'=>'users#index', as: :follower_list
  
  
  
  get 'messages/:speaker/:target'=>"messages#index",as: :messages
  post 'messages/:speaker/:target'=>"messages#create"
  
  post 'users/:id/post_count'=>"users#post_count",as: :post_count
  post 'join/group/:id'=>"groups#join",as: :join_group
  delete 'out/group/:id'=>"groups#out_group",as: :out_group
  
  get 'notice_an_event/:id'=>"groups#notice_an_event",as: :notice_an_event
  post 'notice_an_event/:id'=>"groups#send_email"
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :book_accesses, dependent: :destroy
  validates :title,presence: true,length:{minimum: 1}
  validates :body,presence: true,length:{maximum: 200}
  
  has_one_attached :book_image
end

app/models/book_access.rb
class BookAccess < ApplicationRecord
    belongs_to :book
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    
    
    belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :group_users
    has_many :users , through: :group_users
    belongs_to :owner, class_name: 'User'
    
    has_one_attached :group_image
      
    def get_group_image
        (group_image.attached?) ? group_image : 'no_image.jpg'
    end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
    belongs_to :user
    belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :speaker, class_name: "User"
    belongs_to :target, class_name: "User"
    validates :message, presence: true,length: {maximum: 140}
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites
  has_many :book_comments
  has_many :follows, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follow_members, through: :follows, source: :followed
  has_many :follower_members, through: :followers, source: :follower
  

  
  has_many :group_users
  has_many :groups, through: :group_users, source: :group

  
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  def is_joined(group_id)
    self.groups.where('group_id = ?',group_id).length > 0
  end

  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  
  def is_followed_by(user)
    self.followers.pluck('follower_id').include?(user.id)
  end
  
  def posted_at(day)
    self.books.where('books.created_at like ? ',"%#{day}%")
  end
  
  def days_post(days_ago)
    self.books.where('books.created_at <= ?',days_ago.day.ago).where('books.created_at > ?',(days_ago+1).day.ago)
  end
  
  def todays_post
    self.books.where('books.created_at > ?',1.day.ago)
  end
  
  def predays_post
    self.books.where('books.created_at <= ?',1.day.ago).where('books.created_at > ?',2.day.ago)
  end
  
  def this_week_post
    self.books.where('books.created_at > ?',1.week.ago)
  end
  
  def pre_week_post
    self.books.where('books.created_at <= ?',1.week.ago).where('books.created_at > ?',2.week.ago)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def show
    @book = Book.find(params[:id])
    BookAccess.create(:book_id=>@book.id)
  end

  def index
    @books = Book.left_outer_joins(:favorites)
              .select('books.*','sum(case when favorites.created_at >= "'+1.week.ago.to_s+'" then 1 else 0 end) as favorites_count')
              .group('books.id')
              #.order('favorites_count desc')
              
    if !params[:type]
      @books = @books.order('favorites_count desc')
    elsif params[:type] == 'new'
      @books = @books.order('books.created_at desc')
    elsif params[:type] == 'score'
      @books = @books.order('books.score desc')
    end
    
    if params[:tag] && params[:tag]!=''
      @books = @books.where('tag like ?',"%#{params[:tag]}%")
    end
    
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      @book_tmp = @book
      @user = current_user
      flash.now[:notice] = 'error'
      render 'index'
      #redirect_back fallback_location: root_path
    end
  end

  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body,:score,:tag)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj && obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i>Home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i>Users
            <% end %>
          </li>
          <li>
            <%=  link_to books_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i>Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i>Log out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i>Home
            <% end %>
          </li>
          <li>
            <%= link_to home_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i>About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i>Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i>Log in
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
  
  <% if current_user %>
    <nav class='d-flex'>
    <%= form_with method: :get, url: search_path do |f| %>
      <%= f.text_field :word %>
      <%= f.select :column,['User','Comment'] %>
      <%= f.select :type,['完全一致','前方一致','後方一致','部分一致'] %>
      <%= f.submit '検索' %>
    <% end %>
    
    <%= form_with method: :get, url: books_path do |f| %>
      <%= f.text_field :tag %>
      <%= f.submit 'タグ検索' %>
    <% end %>
  <% end %>
  </nav>
  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/828d915f8a.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main>
        <p id="notice"><%= notice %></p>
     
        <% if @book && @book.errors.any? %>
         
          <div>
            <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      
            <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% elsif @book_tmp && @book_tmp.errors.any? %>
            <div>
            <h2><%= pluralize(@book_tmp.errors.count, "error") %> prohibited this book from being saved:</h2>
      
            <ul>
            <% @book_tmp.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>